apiVersion: v1
kind: Service
metadata:
  name: {{ include "techpotli.fullname" . }}-api
spec:
  selector:
    app: techpotli-api
  ports:
    - port: 3001
      targetPort: 3001
  sessionAffinity: ClientIP
